### PR TITLE
Use batch computation

### PR DESCRIPTION
**Pull request by minsukkahng**
Hi Nikhil,

I have implemented the batch computation. I explicitly create several input matrices, each consisting of a batch of inputs that is directly fed into the graph. It speeds up about 2x. Also, with your continuous efforts making the library faster, training GANs is now super faster.

Cheers,
Minsuk Kahng

---
This change is [Reviewable](https://reviewable.io/reviews/minsukkahng/deeplearnjs/2)

### CODE REVIEW

**Comment by nsthorat** [comment]
It's surprising that we only get a 2x improvement. Maybe we shouldn't display every single tick of the training step, instead do it every 5 or so.

Can you also put a demo up on your github pages? Just push the built files to some static place so I can see if there are any other ways to speed it up :)

This is amazing though! Great work dude

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 74 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-h4aCfBrZlypq6DNsz:-L-h4aCfBrZlypq6DNt-:b7m58nc) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/419270502b5e2a2e4bccf55b322d643741c64088/demos/gan-lab/gan-lab.ts#L74)):*
> ```XML
>   ready() {
>     // HTML elements.
>     this.querySelector('#environment-toggle')!.addEventListener(
> ```

lets get rid of the toggle, no reason to do things on the CPU.

---

*[demos/gan-lab/gan-lab.ts, line 532 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-h4fNq_gDE3qVvrruV:-L-h4fNrGHoIiS609XI7:balhf74) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/419270502b5e2a2e4bccf55b322d643741c64088/demos/gan-lab/gan-lab.ts#L532)):*
> ```XML
>               [{ tensor: this.noiseTensor, data: this.uniformNoiseProvider }]);
> 
>           const maniResult: Float32Array = await result.data() as Float32Array;
> ```

you dont need to specify Float32Array at all, this is inferred.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-:-L-h4wCKc_iyIy1tNZsD:bjuy2x8)*

**Comment by minsukkahng** [comment]
Thank you for your review.

It's much more than 2x improvements compared to what you saw before.  Displaying every 5 steps doesn't help. It may be related to my new comment below about using await.

Here's a link to the demo that runs on GCP: http://bit.ly/2AmjgTk (I'm just running watch-demo. I need your help with creating static HTML files with bundle.js)

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 74 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-h4aCfBrZlypq6DNsz:-L-rPguj0deCaKj3xonU:bss4a2b) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/419270502b5e2a2e4bccf55b322d643741c64088/demos/gan-lab/gan-lab.ts#L74)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

lets get rid of the toggle, no reason to do things on the CPU.
</blockquote></details>

Removed.

---

*[demos/gan-lab/gan-lab.ts, line 532 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-h4fNq_gDE3qVvrruV:-L-rPZb0pS_eDsbbY6Ra:bdol3k2) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/419270502b5e2a2e4bccf55b322d643741c64088/demos/gan-lab/gan-lab.ts#L532)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

you dont need to specify Float32Array at all, this is inferred.
</blockquote></details>

I replaced it with TypedArray. Without this, I got a type error. 

---

*[demos/gan-lab/gan-lab.ts, line 414 at r2](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-rPxOc6X21BJGwtpp7:-L-rPxOc6X21BJGwtpp8:b-l8tfac) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/e64c6e5dc94bdbe874529f737c1a9fadb0ba70a8/demos/gan-lab/gan-lab.ts#L414)):*
> ```XML
>     this.iterationCount++;
> 
>     await this.math.scope(async () => {
> ```

I think I need await to avoid the situation where the next iteration started and NDArray is disposed before the results are visualized.

---

*[demos/gan-lab/gan-lab.ts, line 455 at r2](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-rQjiv3IXRLdayhOlf:-L-rQjiv3IXRLdayhOlg:b-ou1qgk) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/e64c6e5dc94bdbe874529f737c1a9fadb0ba70a8/demos/gan-lab/gan-lab.ts#L455)):*
> ```XML
> 
>         // Visualize discriminator's output.
>         const dData = [];
> ```

I'm not sure whether this pattern (from this line to the next 10 lines) is the best way to implement this, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-:-L-rP6jN6KFbLrxuLLf5:bf2fcu6)*

**Comment by nsthorat** [comment]
:lgtm:

You can just `./scripts/build-demo`

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 455 at r2](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-rQjiv3IXRLdayhOlf:-L-rVrV0FAS50HzT4xYa:bi8qxcu) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/e64c6e5dc94bdbe874529f737c1a9fadb0ba70a8/demos/gan-lab/gan-lab.ts#L455)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

I'm not sure whether this pattern (from this line to the next 10 lines) is the best way to implement this, though.
</blockquote></details>

this seems fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-:-L-rW25P6gie4k1cAAgo:bgrm4p4)*

**Comment by nsthorat** [comment]
Longer term question: do we want to do that UI change that Shan suggested? The sort of "generator" vs "discriminator" UI?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-:-L-rWEB-_hXGw-quF12_:b-4wtwqc)*

**Comment by minsukkahng** [comment]
Doesn't ./scripts/build-demo only create bundle.js? I'm wondering how I can revise index.html and gan-lab.html files. It doesn't seem to work with a HTML with a single line of bundle.js import.

Yes, of course, the next step is to re-design the tool. I have thought about a few ideas and will spend more time over the next few weeks. I will get back to you. Let me know if you have any ideas or suggestions.

**Comment by minsukkahng** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 414 at r2](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-rPxOc6X21BJGwtpp7:-L-rYMz4k40letH0T4im:b-896fix) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/e64c6e5dc94bdbe874529f737c1a9fadb0ba70a8/demos/gan-lab/gan-lab.ts#L414)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

I think I need await to avoid the situation where the next iteration started and NDArray is disposed before the results are visualized.
</blockquote></details>

Done.

---

*[demos/gan-lab/gan-lab.ts, line 455 at r2](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-L-rQjiv3IXRLdayhOlf:-L-rYNkYFREpWpuXw_nJ:b-896fix) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/e64c6e5dc94bdbe874529f737c1a9fadb0ba70a8/demos/gan-lab/gan-lab.ts#L455)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this seems fine
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2)*

**Comment by nsthorat** [comment]
Everything should work out of the box, there is no difference between deploying and watch (watch just watches ts and generates bundle.js on the fly).

What is the problem?

**Comment by minsukkahng** [comment]
Sent you an email.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/2#-:-L-rhIWQIKc2_BFfsjHp:begrtvl)*

**Pull request merged**
