### PR TITLE
Redesign interface, use eager mode

### PR DESCRIPTION
**Pull request by minsukkahng**
Hi Nikhil,

I redesigned the interface based on what I shared with you a couple weeks ago. I also updated code to use the eager mode. 

Please check my email for details. Thank you.

Cheers,
Minsuk (Brian) Kahng

---
This change is [Reviewable](https://reviewable.io/reviews/minsukkahng/deeplearnjs/4)

### CODE REVIEW

**Comment by nsthorat** [comment]
This is *awesome*... I am really looking forward to this :)

Just curious, have you been paying attention to memory? if you use dl.memory().numTensors you can check if you are leaking (if this linearly increases with respect to epochs)

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 1271 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KK00UI-xKNLCL7j6I:-L6KK00UI-xKNLCL7j6J:bn8chad) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1271)):*
> ```XML
>       true);
>     const gfc0B = dl.variable(
>       dl.Tensor1D.zeros([this.numGeneratorNeurons]), true);
> ```

true is the default, no need to pass it, here and everywhere else

---

*[demos/gan-lab/gan-lab.ts, line 1291 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCVVJy2Gm0njCMG1q:-L6KCVVJy2Gm0njCMG1r:b19plp) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1291)):*
> ```XML
> 
>     const gfcLastW = dl.variable(
>       dl.Tensor2D.randNormal(
> ```

s/dl.Tensor2D.randomNormal/dl.randomNormal

here and everywhere else

---

*[demos/gan-lab/gan-lab.ts, line 1335 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCaOQnKkRtW5Cj1Kb:-L6KCaOQnKkRtW5Cj1Kc:bsg136q) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1335)):*
> ```XML
>       true);
>     const dfcLastB = dl.variable(
>       dl.Tensor1D.zeros([1]), true);
> ```

dl.zeros

here and all dl.Tensor1D.zeros()

---

*[demos/gan-lab/gan-lab.ts, line 1377 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KKN2_KUes83ERZ_kH:-L6KKN2_KUes83ERZ_kI:b6vtroi) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1377)):*
> ```XML
>   private modelDiscriminator(inputTensor: dl.Tensor2D): dl.Tensor1D {
>     // Discriminator.
>     const dfc0W = /*this.*/dVariables[0] as dl.Tensor2D;
> ```

hm, what was the problem here? did it say something like "y is not a function of xs"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-:-L6KJN9xznZ1nG5n-yGl:bevpp0d)*

**Comment by nsthorat** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-:-L6MYl_I-WNpKXj3-xbU:bnfp4nl)*

**Comment by nsthorat** [comment]
By the way - high level question, would you mind if you kept this in your own github repository / host it on your own (we can of course still retweet / link to it from our homepage).

We're maintaining too many demos right now / trying to shed some of them and I'm worried about taking another huge one on that we didn't write :)

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-:-L6MYo8r4fbUWuHv0z0o:b-nqhpph)*

**Comment by minsukkahng** [comment]
As for your question about memory leak:
I checked it, and fortunately, there's no leak: the number stays the same! Looks like dl.tidy is doing an awesome job.

As for your question about repository:
Yes, we can use our repository. I agree with you that it's better for me to maintain the code. I would appreciate it if you could just double check from your side.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 1271 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KK00UI-xKNLCL7j6I:-L6YkZzZy_dRifZd_tpn:b-896fix) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1271)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

true is the default, no need to pass it, here and everywhere else
</blockquote></details>

Done.

---

*[demos/gan-lab/gan-lab.ts, line 1291 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCVVJy2Gm0njCMG1q:-L6Ykbwd54LQM3Fj_dV6:b-896fix) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1291)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

s/dl.Tensor2D.randomNormal/dl.randomNormal

here and everywhere else
</blockquote></details>

Done.

---

*[demos/gan-lab/gan-lab.ts, line 1335 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCaOQnKkRtW5Cj1Kb:-L6YkeLyjrHj61X4cY4i:b-896fix) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1335)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

dl.zeros

here and all dl.Tensor1D.zeros()
</blockquote></details>

Done.

---

*[demos/gan-lab/gan-lab.ts, line 1377 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KKN2_KUes83ERZ_kH:-L6YkfXaRbtW53EBHqaV:b-8draqm) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1377)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

hm, what was the problem here? did it say something like "y is not a function of xs"?
</blockquote></details>

As discussed, it was hard to make this work without using global variables. I got the following runtime error: 
Uncaught (in promise) TypeError: Cannot read property 'dVariables' of undefined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-:-L6Yl_Fux_ifLjnezdof:b-4mm9sn)*

**Comment by minsukkahng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[demos/gan-lab/gan-lab.ts, line 1271 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KK00UI-xKNLCL7j6I:-L6YoYJ8X3ELxER5Xhb1:b-236wzt) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1271)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

acknowledge

---

*[demos/gan-lab/gan-lab.ts, line 1291 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCVVJy2Gm0njCMG1q:-L6YoaGCG25pkou_uFUG:b-236wzt) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1291)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

acknowledge

---

*[demos/gan-lab/gan-lab.ts, line 1335 at r1](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4#-L6KCaOQnKkRtW5Cj1Kb:-L6Yoc-Tw97MrUQ2R39N:b-236wzt) ([raw file](https://github.com/minsukkahng/deeplearnjs/blob/3d384f7839fcbf3e0b540682e95431e2cf914ef3/demos/gan-lab/gan-lab.ts#L1335)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

acknowledge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4)*

**Comment by minsukkahng** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/minsukkahng/deeplearnjs/4)*

**Pull request merged**
